### ISSUE TITLE
Normalize quant features

### ISSUE THREAD

**Issue by alhankeser** [alhankeser/kaggle-house-prices#3]

**Comment by claire-vk** [comment]
Use skew() method. 

![image](https://user-images.githubusercontent.com/18402530/50576825-37b9ad80-0de8-11e9-87f6-0df8ca6eb3ae.png)

If skew > 0 then apply box-cox transformation. Looks like he chose 0.75 as a threshold

Note mistake in his code: the code skewness = skewness[abs(skewness) > 0.75] should be written as skewness = skewness[abs(skewness.Skew)>0.75] and only 36 numerical features should be transformed

![image](https://user-images.githubusercontent.com/18402530/50576832-6172d480-0de8-11e9-8bfc-97fe44244c9d.png)
